---
name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: utsav0077/${{ github.event.repository.name }}
      - name: Generate Image Tag from Commit Hash
        id: generate_tag
        run: echo "::set-output name=tag::${GITHUB_SHA:0:7}"
      - name: Generate Image Tag from Epoch
        id: generate
        run: echo "::set-output name=tag::$(date +%s)"
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.generate_tag.outputs.tag }}-${{
            steps.generate.outputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
